In [89]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NeighborhoodComponentsAnalysis


In [90]:
prefix = 'not_denoised'
# prefix = 'denoised'
# prefix = 'noised'
# prefix = 'noise_denoised'
# Load your data into a pandas DataFrame
# Example assuming 'data' is your DataFrame with features and 'target' is your target variable
df = pd.read_csv(f'Feature Extracted/{prefix}_feature_extracted.csv')
df

Index           Eye ID Final Label   type    diss_R    homo_R  \
0         0  TRAIN050022.JPG         NRG  TRAIN  2.252315  0.376308   
1         1  TRAIN003399.JPG         NRG  TRAIN  3.274909  0.293906   
2         2  TRAIN011846.JPG         NRG  TRAIN  1.774728  0.511339   
3         3  TRAIN005388.JPG         NRG  TRAIN  3.982364  0.430551   
4         4  TRAIN035358.JPG         NRG  TRAIN  3.523542  0.284514   
...     ...              ...         ...    ...       ...       ...   
6535   6535  TRAIN100337.JPG          RG   TEST  3.476439  0.274419   
6536   6536  TRAIN100712.JPG          RG   TEST  4.955371  0.241892   
6537   6537  TRAIN100794.JPG          RG   TEST  4.072778  0.224629   
6538   6538  TRAIN101006.JPG          RG   TEST  1.903099  0.508135   
6539   6539  TRAIN101020.JPG          RG   TEST  3.508398  0.290117   

          cont_R    ener_R     ASM_R    corr_R  ...      cont_G    ener_G  \
0      12.325124  0.061846  0.003825  0.949571  ...   10.603096  0.091785   
1      19.348257  0.062444  0.003899  0.985083  ...   14.321534  0.046974   
2      22.546463  0.131765  0.017362  0.994057  ...   38.361386  0.125378   
3     227.071037  0.140931  0.019862  0.975797  ...  189.021353  0.142668   
4      25.660268  0.040662  0.001653  0.972398  ...   49.179379  0.042726   
...          ...       ...       ...       ...  ...         ...       ...   
6535   22.794009  0.047062  0.002215  0.979056  ...   95.800885  0.028972   
6536   67.060046  0.027888  0.000778  0.990075  ...   70.053212  0.043619   
6537   28.711824  0.028825  0.000831  0.965651  ...   41.721096  0.031449   
6538   10.584581  0.173450  0.030085  0.995260  ...   31.559672  0.028931   
6539   27.460475  0.035150  0.001236  0.990247  ...   18.325563  0.064149   

         ASM_G    corr_G    diss_B    homo_B     cont_B    ener_B     ASM_B  \
0     0.008425  0.862111  2.035349  0.392488   8.564927  0.098016  0.009607   
1     0.002207  0.941072  3.253471  0.259573  17.157841  0.055375  0.003066   
2     0.015720  0.994405  1.834674  0.529266  39.368698  0.121301  0.014714   
3     0.020354  0.971020  2.472860  0.509133  68.719440  0.137941  0.019028   
4     0.001826  0.914004  3.692820  0.261155  26.761083  0.057909  0.003353   
...        ...       ...       ...       ...        ...       ...       ...   
6535  0.000839  0.984483  4.527610  0.232778  43.735296  0.043331  0.001878   
6536  0.001903  0.985217  2.862218  0.324295  16.457594  0.085611  0.007329   
6537  0.000989  0.958497  3.539737  0.254851  22.192127  0.042538  0.001810   
6538  0.000837  0.989597  2.687700  0.331775  12.889076  0.039324  0.001546   
6539  0.004115  0.965410  2.153896  0.369884   8.091643  0.110793  0.012275   

        corr_B  
0     0.850266  
1     0.829560  
2     0.994090  
3     0.968490  
4     0.903013  
...        ...  
6535  0.986567  
6536  0.973629  
6537  0.947828  
6538  0.991598  
6539  0.805825  

[6540 rows x 22 columns]

In [91]:
df_train = df[df['type'] == 'TRAIN'].copy().reset_index(drop=True)
df_val = df[df['type'] == 'VAL'].copy().reset_index(drop=True)
df_test = df[df['type'] == 'TEST'].copy().reset_index(drop=True)

In [92]:
X_train = df_train.drop(columns=['Index', 'Final Label', 'Eye ID', 'type'])  # Features
y_train = df_train['Final Label']  # Target

X_val = df_val.drop(columns=['Index', 'Final Label', 'Eye ID', 'type'])  # Features
y_val = df_val['Final Label']  # Target

X_test = df_test.drop(columns=['Index', 'Final Label', 'Eye ID', 'type'])  # Features
y_test = df_test['Final Label']  # Target
y_val

0      NRG
1      NRG
2      NRG
3      NRG
4      NRG
      ... 
995     RG
996     RG
997     RG
998     RG
999     RG
Name: Final Label, Length: 1000, dtype: object

In [93]:
# Initialize NCA
nca = NeighborhoodComponentsAnalysis(n_components=10 ,random_state=42)
# nca = NeighborhoodComponentsAnalysis(random_state=42)

# Fit NCA to the data
nca.fit(X_train, y_train)

NeighborhoodComponentsAnalysis(random_state=42)

In [94]:
# Optionally, you can retrieve the selected features
selected_features = np.argsort(nca.components_)

print("Selected features:", selected_features)

Selected features: [[14  8  1 17  7  9  3 13 15 11 10 16  4  5  2 12  6  0]
 [ 2  0  6 12  5  4 16 10 11 17  3 13 15  9  7  8 14  1]
 [ 6 15 13  3  1  9 16 11  7 10  4 17  0  5  8 14 12  2]
 [ 2  0  6 12 17  4 11 16 10  5 13  7  1  9 15  8 14  3]
 [ 2  6  0 12 17 11  3 16 10  8  5  1 13  9 15  7 14  4]
 [14  8 12  0  6 11 17  7 16 10  9 13 15  1  4  3  2  5]
 [ 2 17  7 13  1 11  9 15  3 10  4 16  5 12 14  0  8  6]
 [ 6  0 12 14  2  5 16  4 10 11  3 17 15  9  1 13  8  7]
 [ 0 12 15 16  5 10  9  4  3 11 14  7 13  1  2 17  6  8]
 [ 2  0  6 12 17  8  5 11 16 10  4 15 13  3  7  1 14  9]
 [ 2  0  6 12  8 17  5 11 16  4 15  9  3 13  7  1 14 10]
 [ 6  2  0 12  5 10 16  4  9  3 15  1 13  7 17  8 14 11]
 [ 8  7 13 17  9 11  1 15  5 10 16  3  4  0  2  6 14 12]
 [ 2  6 14 12  0  5 16  4 10 17 11  3 15  9  1  7  8 13]
 [ 0  5 13  7  8 16 11 10 15  9  4  1  2 17  3  6 12 14]
 [ 2  0  6 12  8 17  5 16 11 10  4 13  9  3  7  1 14 15]
 [ 2  0  6  8 12 17  5 11 10  4 15  9 13  3  7  1 14 16]
 [ 6  0 12  

In [95]:
# Transform the data using the learned transformation
X_train_transformed = nca.transform(X_train)

temp = pd.DataFrame(X_train_transformed)
temp['Final Label'] = y_train
temp

temp.to_csv(f'Feature Selected\{prefix}_feature_selected_train.csv', index=False)

In [96]:
# Transform the data using the learned transformation
X_val_transformed = nca.transform(X_val)

temp = pd.DataFrame(X_val_transformed)
temp['Final Label'] = y_val
temp

temp.to_csv(f'Feature Selected\{prefix}_feature_selected_val.csv', index=False)

In [97]:
# Transform the data using the learned transformation
X_test_transformed = nca.transform(X_test)

temp = pd.DataFrame(X_test_transformed)
temp['Final Label'] = y_test
temp

temp.to_csv(f'Feature Selected\{prefix}_feature_selected_test.csv', index=False)